name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

  # Cho phép chạy bằng tay trên web Github
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          # Điền tên User và Tên Space của bạn ở Hugging Face vào đây
          HF_USERNAME: nhatquan222
          HF_SPACE_NAME: Sleep-Stage-Classifier
        run: |
          cd PipelineEEG
          # Tạo một repo git ảo chỉ chứa code của PipelineEEG
          git init
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          # Cấu hình Git LFS cho file trọng số model (.pth)
          git lfs install
          git lfs track "*.pth"
          git add .gitattributes
          
          git add .
          git commit -m "Auto Deploy from Github Actions"
          # Force push toàn bộ thư mục PipelineEEG lên nhánh main của Hugging Face
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME HEAD:main --force
